---
- name: Patching RHEL 9.0 VM
  hosts: all
  become: yes  # Use elevated privileges (sudo)
  gather_facts: yes
  vars:
    reboot_rhel: false  # Variable to track if a reboot is required

  tasks:
    - name: Check if DNF is available
      command: dnf --version
      register: dnf_installed
      changed_when: false

    - name: Ensure DNF is installed
      dnf:
        name: dnf
        state: present
      when: dnf_installed.rc != 0

    - name: Update all packages on RHEL 9.0 VM
      dnf:
        name: "*"
        state: latest
        update_only: yes

    - name: Check if a reboot is required (RHEL 9.0)
      command: needs-restarting -r
      register: reboot_required_rhel
      failed_when: false

    - name: Set reboot flag if reboot is required
      set_fact:
        reboot_rhel: true
      when: reboot_required_rhel.rc == 1

    - name: Reboot RHEL VM if required
      reboot:
        msg: "Reboot initiated by Ansible after patching"
      when: reboot_rhel | bool

    - name: Ensure log directory exists
      file:
        path: /var/log/ansible
        state: directory
        mode: '0755'

    - name: Log patching results
      lineinfile:
        path: /var/log/ansible/patching.log
        line: "{{ inventory_hostname }} - RHEL 9.0 patched successfully"
        create: yes
