---
- name: VM Creation
  hosts: localhost
  tasks:
  - name: Create RHEL 9.0 VM - PraveenTEST-02
    os_server:
       state: present
       name: PraveenTEST-02
       image: "rhel-9.0-cl"
       key_name: k8s
       timeout: 200
       flavor: 11fb575e-0a42-4911-a684-f9f2b6eb9af9
       auto_ip: no
       network: 7ef4c191-a7dd-4b75-8f9d-31df32b86291
       security_groups: default
       meta:
         os: rhel

- name: Patching RHEL 9.0 VM
  hosts: all
  become: yes  # Use elevated privileges (sudo)
  gather_facts: yes
  vars:
    reboot_rhel: false  # Variable to track if a reboot is required

  tasks:
    - name: Check if DNF is available
      command: dnf --version
      register: dnf_installed
      changed_when: false

    - name: Ensure DNF is installed
      dnf:
        name: dnf
        state: present
      when: dnf_installed.rc != 0

    - name: Update all packages on RHEL 9.0 VM
      dnf:
        name: "*"
        state: latest
        update_only: yes

    - name: Check if a reboot is required (RHEL 9.0)
      command: needs-restarting -r
      register: reboot_required_rhel
      failed_when: false

    - name: Set reboot flag if reboot is required
      set_fact:
        reboot_rhel: true
      when: reboot_required_rhel.rc == 1

    - name: Reboot RHEL VM if required
      reboot:
        msg: "Reboot initiated by Ansible after patching"
      when: reboot_rhel | bool

    - name: Ensure log directory exists
      file:
        path: /var/log/ansible
        state: directory
        mode: '0755'

    - name: Log patching results
      lineinfile:
        path: /var/log/ansible/patching.log
        line: "{{ inventory_hostname }} - RHEL 9.0 patched successfully"
        create: yes
